services:

  nginx:
    build: docker/nginx
    container_name: 'book_catalog_nginx'
    restart: always
    working_dir: /app
    expose:
      - 80
    volumes:
      - ./:/app
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php
    networks:
      - backend
      - nginx-proxy_nginx-proxy
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME}
      - TZ=${WORKSPACE_TIMEZONE}

  php:
    container_name: 'book_catalog_php'
    build: ./docker/php
    volumes:
      - ./:/app
      - ./logs/php:/var/log
      - ./logs/yii:/app/runtime/logs
      - ./logs/xdebug:/tmp/xdebug
    working_dir: /app
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=docker}
    env_file:
      - ./.env
    networks:
      - backend

  db:
    container_name: 'book_catalog_db'
    image: percona:8.0.40-31
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend

  redis:
    image: "redis:alpine"
    container_name: 'book_catalog_redis'
#    command: redis-server --requirepass sOmE_sEcUrE_pAsS

#    ports:
#      - "6379:6379"

    volumes:
      - ./redis-data:/var/lib/redis
#        - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - backend

networks:
  backend:
  nginx-proxy_nginx-proxy:
    external: true